### PR TITLE
Add channel binding functionality

### PR DESCRIPTION
**Pull request by DarkStoorM**
Allows binding commands to the channel / multiple channels

No changes are required if the command can be executed in every channel

Automatically handles the command rejection if the channel binding for a new command is present in the bindings configuration file.

Once new command is added, it will be validated with each request before execution - **it is important to specify a valid discord channel_id or the command will never get executed**

```js
const channelBindings = {
    "!coinflip": process.env.BINDING_COINFLIP,
    "!8ball": process.env.BINDING_8BALL,
};
```

Requires initial setup in the Environment: BINDING_[COMMAND_NAME]=CHANNEL_ID
* BINDING_COINFLIP = 123456789012345

or

* BINDING_COINFLIP = 123456789012345,123456789012345,123456789012345

**Naming and the configuration location should be taken into consideration**

### CODE REVIEW

**Comment by dcepil** [comment]
[Allow binding commands to channels](https://trello.com/c/fugbbQrf/32-allow-binding-commands-to-channels)

**Review by VuongRon — COMMENTED** [review]
Overall looks really good. The only suggestion I will make is to rework the config so you only have to modify 1 file (hopefully `.env`) instead of 2.

I would recommend having a naming scheme that can be broken down in order to determine the command; something like:

```
COINFLIP_CHANNEL_BINDING = 12345,67890
```

in `.env`. Then your channel binding service can filter through `Object.keys(process.env)` for vars with `'_CHANNEL_BINDING'` in the name. Then you can loop through that subset of keys to populate your `channelBindings` object. I think this effort is worth it to prevent misconfiguration in 2 places.

Alternatively, it could be worthwhile to have a `channelBindings` table in the DB and we can just write a seed file to populate the table, and write migrations to make modifications as needed. In this approach you can easily create a model for the channel binding as well which will replace your channel binding service.

Let me know if you think either is a stupid idea.

**Comment by DarkStoorM** [comment]
I see, we can even skip the additional config and just add an `init` function to the binding service, replacing the `if` from the index. Sounds cleaner 👍 
I will try that later

**Comment by DarkStoorM** [comment]
Tested in the following environment:

image

- with no channel bindings specified, command could be executed from every channel
- having the channel bindings specified for `arena` and `inventory`, the command could only be executed in those channels, ignored in every other channel

**Review by VuongRon — APPROVED** [review]
Looks good 👍

**Pull request merged**
